### ISSUE TITLE
How to build bluetooth example app with auto PROVISION mesh device?

### ISSUE THREAD

**Issue by jiqianghu** [ambiot/ambz2_matter#108]
Many devices boot up with default app/net key etc. NOT need phone app or AT command to config.  Example mesh app: component/common/bluetooth/realtek/sdk/example/bt_mesh_device_rtk_demo/

**Comment by step0035** [comment]
hi @jiqianghu, thanks for your interest in the project. However this repository only focuses on Matter related issues, you can direct general SDK issues here: https://github.com/ambiot/ambz2_sdk.
