### ISSUE TITLE
[wifi] do a wifi disconnect inside factory reset

### ISSUE THREAD

**Issue by step0035** [ambiot/ambz2_matter#128]
- if we have previously connected to a wpa3 ap, it is not enough to clear wifi info in flash
- the next time we try to connect to an ap, it will fail, but the subsequent retry will pass
- better to put wifi disconnect in factory reset function

**Comment by xshuqun** [comment]
In #69 I mentioned to add sys_reset() before that please do a wifi_disconnect().
