### ISSUE TITLE
add timer for identify cluster on portinglayer example

### ISSUE THREAD

**Issue by step0035** [ambiot/ambz2_matter#133]
- portinglayer examples have identify callbacks but no timer

**Comment by step0035** [comment]
looks like it is added, need to test
@SirRu24 - please help to test if the timer is counting down when you do the below command
`./chip-tool identify identify 60 1 1'

**Comment by SandyYeow** [comment]
checked with ameba z2 and identify cluster will counting down. May refer to the log file.
[identify-cluster.log](https://github.com/ambiot/ambz2_matter/files/12544749/identify-cluster.log)
