### ISSUE TITLE
Error in RNG in mbedtls file

### ISSUE THREAD

**Issue by samryanuofl** [ambiot/ambz2_matter#186]
https://github.com/ambiot/ambz2_matter/blob/f808fd8819f46432e6177159db6b7839bf02abad/component/common/network/ssl/mbedtls-matter/library/ctr_drbg.c#L598-L611

Missing semicolon at the end of this line causes a compilation error if this code is enabled.
```C
ret = 0xac // CHIP_ERROR_INTERNAL 
```

Also, should there be context protection here? Like 

```C
device_mutex_lock(RT_DEV_LOCK_CRYPTO);
int ret = crypto_init(); 
if (ret != SUCCESS) 
{ 
   printf("crypto_init() failed\r\n"); 
   device_mutex_unlock(RT_DEV_LOCK_CRYPTO);
   return ret; 
} 
  
ret = crypto_random_generate(output, output_len); 
device_mutex_unlock(RT_DEV_LOCK_CRYPTO);
if (ret != 0) 
    ret = 0xac; // CHIP_ERROR_INTERNAL 

return ret;
#else
```

**Comment by xshuqun** [comment]
@samryanuofl Thanks for informing. PR has been created to fix the issue https://github.com/ambiot/ambz2_matter/pull/188.
Please do check it, and close the issue if there is no further question on it.
