### ISSUE TITLE
[BLE] allocate fail when using mesh

### ISSUE THREAD

**Issue by xshuqun** [ambiot/ambz2_matter#34]
After booting upon factory reset, use at command to connect wifi, and following logs will be shown:
`[BT Mesh Device] bt_mesh_device_matter_adv_timer_handler allocate padv_data fail ! `

After sometime, the following logs will be displayed:
```
chip[CSL] PacketBuffer: allocation too large.
chip[IN] No memory to flatten incoming packet buffer chain of size 1451
```

Full log as attached
[matter ble mesh.txt](https://github.com/ambiot/ambz2_matter/files/10350595/matter.ble.mesh.txt)

**Comment by 2UBBISH** [comment]
Hi, I've run into the same issue. Could you please let me know how to fix it?
