### ISSUE TITLE
[ble] after factory reset, advertise ble again

### ISSUE THREAD

**Issue by step0035** [ambiot/ambz2_matter#69]
- after factory reset, should we start advertise ble again?
- currently need to reboot to start advertising again

**Comment by AdamZhang0124** [comment]
What specific applications require this response?

**Comment by AdamZhang0124** [comment]
We can add it, I think it's a good practice to make device always discoverable when it is not commissioned.

**Comment by step0035** [comment]
it is not application specific, but received feedback from multiple customers to have this feature

**Comment by xshuqun** [comment]
@SirRu24 Please add sys_reset() in ATM$ so that after factoryreset, the board will auto reboot.
