### ISSUE TITLE
Lighting-app Example commissioning problem

### ISSUE THREAD

**Issue by saintlee1107** [ambiot/ambz2_matter#87]
Hi I have a problem with commissioning problem.

I was referring to the documentation In application/matter/example/light/README.md .
I Checked  `CONFIG_EXAMPLE_MATTER` and `CONFIG_EXAMPLE_MATTER_LIGHT` was enabled  in `platform_opts.h`.
And `CONFIG_EXAMPLE_MATTER_CHIPTEST` was disabled.

I did make light And make is_matter.

I Flashed the Image and Test with Chip_Tool APP

but, Panic rised at the final stage of commissioning.

------------------- Panic result -------------------------------------------

xQueueGenericSend
/ambz2_matter/project/realtek_amebaz2_v0_example/GCC-RELEASE/../../../component/os/freertos/freertos_v10.0.1/Source/queue.c:846
0x9b02e3f7
xQueueGetMutexHolder
/ambz2_matter/project/realtek_amebaz2_v0_example/GCC-RELEASE/../../../component/os/freertos/freertos_v10.0.1/Source/queue.c:544
0x9b084b6d
_ZNK4chip11DeviceLayer8Internal35GenericPlatformManagerImpl_FreeRTOSINS0_19PlatformManagerImplEE33_IsChipStackLockedByCurrentThreadEv
/ambz2_matter/component/common/application/matter/example/light/../../../../../../third_party/connectedhomeip/src/include/platform/internal/GenericPlatformManagerImpl_FreeRTOS.ipp:166 (discriminator 4)
0x9b07d6d1
_ZNK4chip11DeviceLayer15PlatformManager32IsChipStackLockedByCurrentThreadEv
/ambz2_matter/component/common/application/matter/example/light/../../../../../../third_party/connectedhomeip/src/include/platform/PlatformManager.h:355
0x9b080f5b
_ZN12_GLOBAL__N_121EntryIteratorDelegate4NextERN4chip6Access13AccessControl5EntryE
/connectedhomeip/examples/lighting-app/ameba/build/chip/../../../../../config/ameba/third_party/connectedhomeip/src/access/examples/ExampleAccessControlDelegate.cpp:841
0x9b0577b3
_Z29emberAfWriteAttributeExternaltmmPhh
/ambz2_matter/component/common/application/matter/example/light/../../../../../../third_party/connectedhomeip/src/app/util/attribute-table.cpp:56
0x9b058511
_ZN4chip3app22WriteSingleClusterDataERKNS_6Access17SubjectDescriptorERKNS0_25ConcreteDataAttributePathERNS_3TLV9TLVReaderEPNS0_12WriteHandlerE
/ambz2_matter/component/common/application/matter/example/light/../../../../../../third_party/connectedhomeip/src/app/util/ember-compatibility-functions.cpp:1029

------------------------------------------------------------------------------------------------------------

how to solve this situation? help me.

**Comment by step0035** [comment]
@saintlee1107, can you provide the full device log, chiptool log, connectedhomeip SHA and ambz2_matter SHA?
Also, what chipset are you using?

**Comment by saintlee1107** [comment]
@step0035 
> @saintlee1107, can you provide the full device log, chiptool log, connectedhomeip SHA and ambz2_matter SHA? Also, what chipset are you using?

thank you for the quick reply.

I'm using RTL8720CM.

ambz2_matter      SHA  :1494224e6dc35f76347d1bea1ff0572e769da36f
connectedhomeip SHA : a82ea1155c4253ded2000825b3a582981662a400

sorry, i used samsung smartThings Stations.

--------------------------------------------full device log ---------------------------------------

[LOG.zip](https://github.com/ambiot/ambz2_matter/files/11026367/LOG.zip)

thanks.

**Comment by step0035** [comment]
@saintlee1107, the commission is successful, but smartThing station send some commands that caused the hardfault. Can you find out what are the commands sent by smartThing station?

**Comment by step0035** [comment]
@saintlee1107 we have tried commissioning with smartthings and it was successful, closing this issue. Reopen if you have further issues.
